
'''
In [4]: a['distance']
Out[4]: 17603.7

In [5]: a['elapsed_time']
Out[5]: 3645

In [6]: a['timezone']
Out[6]: '(GMT+08:00) Asia/Shanghai'

In [7]: a['calories']
Out[7]: 339.0

In [8]: a['total_elevation_gain']
Out[8]: 44.0

In [9]: a['startdate']
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-92d40b0218f1> in <module>
----> 1 a['startdate']

KeyError: 'startdate'

In [10]: a['start_date_local']
Out[10]: '2020-11-11T20:57:40Z'

''' 

